name: Docker Image Creation

on:
  push:
    branches:
      - container-image
      
env:
  WORKSPACE: ${{ github.workspace }}
  JFROG_USERNAME:  ${{ secrets.JFROG_USERNAME }}
  JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  Docker-Image-Creation:
    runs-on: [self-hosted, sanofi-chc-github_standalone_runner_01]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'
          ref: container-image

      - name: Docker Image Creation and Upload
        run: |
          cd ${WORKSPACE}/build-images/v1.0.0/sanofi-chc-build-base/
          bash ${WORKSPACE}/cicd-scripts/docker-image-upload.sh sanofi-chc-build-base v1.0.0
